### PR TITLE
Provide ability to override FragmentTransaction creation.

### PR DESCRIPTION
**Pull request by IlyaGulya**
For example, to provide animation to transaction.

### CODE REVIEW

**Comment by terrakok** [comment]
Good idea!
But make it for `FragmentNavigator.java` plz.
And write JavaDoc

**Comment by IlyaGulya** [comment]
Done :smile:

**Comment by terrakok** [comment]
"For example, to add animations to transaction."
What another do you can add to transaction (exclude animation)?

May be create specific method only for animation:
```java
private FragmentTransaction createTransaction() {
    final FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
    applyAnimation(fragmentTransaction);
    return fragmentTransaction;
}

protected void applyAnimation(final FragmentTransaction fragmentTransaction) {
    //do nothing
}
```

What are you think?

**Comment by IlyaGulya** [comment]
Done!

**Comment by terrakok** [comment]
Boolean flags are redundant because default animation value is '0'
See: [BackStackRecord.java](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.1_r1/android/app/BackStackRecord.java#179)

**Comment by IlyaGulya** [comment]
Done!

**Comment by terrakok** [comment]
This feature works not obvious for "Replace" command.  Needs to be rejected for now

**Pull request closed without merging**
