### PR TITLE
Extracting base navigation logic for Navigators (backwards compatable)

### PR DESCRIPTION
**Pull request by olegivo**
1. Extracting base navigation logic for Navigators.
Using template method and adapter pattern. Now instead of override all command processing logic inheritors available to pointwise override only part of command processing that needs. Moving lot of boilerplate code from main navigation logic.
2. Removing AppNavigators inheritance from FragmentNavigators. Was look strange that instead of implements own navigation logic for activity navigation there was extending fragment navigation.

### CODE REVIEW

**Comment by Jeevuz** [comment]
Hi! To be honest, I don't really understand the intent and profit of this changes. With them we will add many additional "base" entities where we wanted to provide only concrete ones, just to ease the lives and nothing more. If one want change something he could just by writing his own implementation. I think there is no need for base classes here.
Could you please tell your motivations?

By the way we already had wery similar PR.

**Comment by olegivo** [comment]
Hi! Since only 1th paragraph raised your questions, I'll explain it separately.
Main motivation is to make behavior extension of navigators more concrete and easy. If your question is only about additional entities, there may be the same approach with template methods without "base" entity and can be achieved easy just by pushing templates methods down to descendants.

**Comment by Jeevuz** [comment]
I got it, thanks. But me and @terrakok intentionally made the FragmentNavigator a one class with just the default implementation. Because the library not intended to be used only with default navigators and it was just a helper to start easy with the default. Our goal was to push one to write his own specific navigators needed for their specific goals. But the default implementation was recommended itself as good citizen and evolved. And as I see now it is used by many people.
So I understood your proposition to make it more easily extendable. But personally I want it to stay one-class implementations.
Also there is some problems to made the methods like applyForward and so on. Forward is just command, and one can add his own specific command. So the methods will not stay relevant and he will be forced to override the applyCommand anyway.

Regarding your second point: the inheritance here is intentional, because we don't want to made the separate Activity navigation, as explicitly stated in the javadoc. Activity navigation is something bigger because there is intent flags. So what we have in AppNavigator is just FragmentNavigator + some activity using possibilities.

**Comment by olegivo** [comment]
> So I understood your proposition to make it more easily extendable. But personally I want it to stay one-class implementations.

As mentioned above, this is not a problem and one-class implementation can be achieved easy from current point)
> Also there is some problems to made the methods like applyForward and so on. Forward is just command, and one can add his own specific command. So the methods will not stay relevant and he will be forced to override the applyCommand anyway.

In case of developer will add his own command, other methods will still relevant as it is _another (his own)_ command not intersects with other commands and methods. Ever without changes from this PR developer _must_ override applyCommand anyway if he want his command to apply.
applyForward-like methods are not in the Navigator interface, but in concrete default implementations. I suppose that most of developers use this default implementation. If needing of pointwise overriding they must override whole applyCommand, i.e. copy-paste all applyCommand implementation and changing part of it, even if they want to override just part of it. This situation most probably, especially if the default implementation evolved and changed but his overriding - not. That can be potentially break expecting behavior cause overriding desync of default implementation.

> Regarding your second point: the inheritance here is intentional, because we don't want to made the separate Activity navigation, as explicitly stated in the javadoc. Activity navigation is something bigger because there is intent flags. So what we have in AppNavigator is just FragmentNavigator + some activity using possibilities.
I assume that Activity navigation is something bigger that Fragment navigation, but why ActivityNavigator _is_ FragmentNavigator? ActivityNavigator overrides all methods that supported by Activity navigation but not supported methods will still work with some fragment. This breaking understanding and responsibility of ActivityNavigator. I suppose that FragmentNavigator and ActivityNavigator are completely different and must have different implementation as Activity navigation does not imply Fragment navigation especially in default implementation.

**Comment by Jeevuz** [comment]
> if the default implementation evolved and changed but his overriding - not. That can be potentially break expecting behavior cause overriding desync of default implementation.

If we change default it is better for the user to have his own implementation not changed. Because otherway it can break his navigation. 

> i.e. copy-paste all applyCommand implementation and changing part of it
Yep. And he will do it by himself and will not be harmed by unexpected behavior. Because if he overrides one command that used in conjunction with another (eg backTo with Replace for newRoot) some functionality can break.

Also, what is your point to override this default commands implementations? What you think the user could want to change there?

>ActivityNavigator is FragmentNavigator?
That's why we called it AppNavigator. It's not the activity navigation. 
How you see the methods like BackTo for separate ActivityNavigator? And how do you see work with mixed activity and fragments navigation when using separated navigators?

**Comment by olegivo** [comment]
> That's why we called it AppNavigator. It's not the activity navigation.
How you see the methods like BackTo for separate ActivityNavigator? And how do you see work with mixed activity and fragments navigation when using separated navigators?

Now it's clear, but not so obvious)

> what is your point to override this default commands implementations? What you think the user could want to change there?

I think that user could change for example only forward and replace commands implementations (as most probably overridable) without forcing him to copy-pasting all other command applying implementation.

**Comment by terrakok** [comment]
Ready navigators are not made for expansion. It is only for study and use "as is". In other cases, you must write your own navigator.

**Pull request closed without merging**
