### PR TITLE
Fix NPE when localStackCopy.size() == 0 and FragmentFactory is used

### PR DESCRIPTION
**Pull request by adolgiy**

### CODE REVIEW

**Comment by asitnkova** [comment]
Thanks for spotting that bug. The implementation looks good to me.  But I think replaces in `fragmentForward()` should also be rewritten to use `fragmentReplaceInternal()`.

**Comment by adolgiy** [comment]
Done! Also add explicit exception to be more specific on what was wrong.

**Comment by adolgiy** [comment]
Looks like `fragmentForward(Forward)` can be extracted to another method and reused in `fragmentReplace(Replace)` for `localStackCopy.size() > 0` branch. 

[Forward - 101..118](https://github.com/terrakok/Cicerone/blob/master/library/src/main/java/ru/terrakok/cicerone/android/support/SupportAppNavigator.java#L101..L118) and [Replace - 158..178](https://github.com/terrakok/Cicerone/blob/master/library/src/main/java/ru/terrakok/cicerone/android/support/SupportAppNavigator.java#L158..L178)

**Comment by asitnkova** [comment]
I think yeah, it could be extracted.

**Comment by olegivo** [comment]
I also catch the bug and wanted to fix it, but found this PR.
@asitnkova Is there any forecasts on when the PR will be accepted?

**Comment by asitnkova** [comment]
@olegivo I'm not one of the maintainers of Cicerone, so I can't make any promises
@terrakok Could you release hotfix 5.1.1 with this PR in it?

**Pull request merged**
