### PR TITLE
Replace instaceof checks

### PR DESCRIPTION
**Pull request by sboishtyan**
Can we avoid to use instance of checks in that way? I think, our performance will be better and code more readable.

### CODE REVIEW

**Comment by grine4ka** [comment]
Oh, I think that's a good idea! Using instanceof is considered to be a bad practice

**Comment by terrakok** [comment]
In your case for adding new command I must do:
1) Extend new ```Command``` class
2) Create new ```CommandType``` class with all commands (can't add)
3) Change all other classes
4) ...

Using instanceof is a bad practice because you can pass any class instance usually.
But this case your classes are limited to a ```Command``` interface marker.

**Comment by sboishtyan** [comment]
If problem is flexibility, I can add new type Custom and method applyCustomCommand.

**Comment by Jeevuz** [comment]
Why you say instanceof is bad practice?

About this PR - I deffinitely don't want to introduce this into the library, because it breaks flexibility.
And this is too heavy change just to remove few instanceof calls. What the pros of this?

Btw, just use Kotlin and your code will be 200% readable with the when operator.

**Comment by sboishtyan** [comment]
Instanceof is bad because runtime checks not safe and we don't know our problems before deploy and start app. PS I only want to discuss about my vision and realize yours.

**Comment by terrakok** [comment]
All classes for instanceof check must be extended from ```Command```.
And this allows the library to be easily extensible.

**Comment by Jeevuz** [comment]
Yep, instanceof using can sometime be bad and signal that solution must be rethinked. 
But here we need a set of commands that can be extended. Enum not give us this possibility. Marker interface (Command in our case) give us the type safety we need to not allow pass anything except it to the applyCommand. And also it is easy to add new command without need of changing any additional code (in your proposal we need to change switch in CommandBuffer, add methods in Navigator...). So the use of instanceof checks is really small cost to get that flexibility. 
We could add the tag in Command, but it introduces additional work when extending, but gives no real profit. 
So in my opinion the problem of using the instanceof here is illusory.

**Comment by sboishtyan** [comment]
Ok, thanx u for discussion

**Pull request closed without merging**
