### PR TITLE
Feature/activity animations

### PR DESCRIPTION
**Pull request by Popalay**

### CODE REVIEW

**Comment by Jeevuz** [comment]
Hi, thanks for the PR! 
For me it seems totally ok. @terrakok, what you think?

**Comment by terrakok** [comment]
1) It's better to rename setupActivityTransactionAnimation to createStartActivityOptions.
2) Why transfer the intent to this method?

**Comment by Popalay** [comment]
Shared element transition need some parameters which put into intent

**Comment by terrakok** [comment]
This params you can get from command data. I'm right?

**Comment by Popalay** [comment]
@terrakok Yes, but I didn't want to mix it

**Comment by terrakok** [comment]
Don't pass animation parameters inside the data!
1) You can identify transition by navigation Command
2) Navigator can take all needed params directly from Activity

Look it here: https://github.com/terrakok/Cicerone/blob/develop/sample/src/main/java/ru/terrakok/cicerone/sample/ui/animations/ProfileActivity.java#L101

**Comment by Popalay** [comment]
@terrakok This works only with fragments

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by terrakok** [comment]
"we must put some parameters into bundle" - How do you get these parameters?
You create Intent for Activity in the createIntent method. This method gets into the parameters only screen key and data.
Why can you create data for intent there but not in createStartActivityOptions?

**Comment by Popalay** [comment]
I can. But your question is: "Why do I need intent in createStartActivityOptions?" To put transition parameters into intent extra. I can put this parameters in the createActivityIntent, but I thought, that is bad idea - mixing navigation and transition parameters.

**Comment by terrakok** [comment]
Ok! I understud)

**Pull request merged**
