### PR TITLE
Add transaction type into `setupFragmentTransaction` method

### PR DESCRIPTION
**Pull request by AlexeyKorshun**

### CODE REVIEW

**Comment by AlexeyKorshun** [comment]
@terrakok will you check this PR?

**Comment by terrakok** [comment]
Looks good to me. But what do you think about moving `clearContainer` parameter from router.navigateTo method to `FragmentScreen` property? My opinion is describing fragment transaction option in FragmentScreen will be more logical

**Comment by AlexeyKorshun** [comment]
Hm, I don't think so right now, I think screens should not know about transaction type, it is not about screen, but I will think about it.

**Comment by terrakok** [comment]
FragmentScreen is combination key and fragment  factory at the moment. And i think that description of transaction details must be described here too

**Comment by AlexeyKorshun** [comment]
Maybe you are right :)

**Comment by AlexeyKorshun** [comment]
@terrakok but it is not for this PR I think, it is another task

**Comment by terrakok** [comment]
https://github.com/terrakok/Cicerone/commit/daef586461e8c0c4f03d8251641bec51392e8a27
https://github.com/terrakok/Cicerone/commit/4fc5b26980b270c02913da9d9bb034b1b6c59b4f

**Pull request closed without merging**
