### PR TITLE
Cicerone migrated to Kotlin

### PR DESCRIPTION
**Pull request by OsipXD**
This Pull Request also contains #55

**Changes:**
* All code converted to Kotlin (with JVM compatibility annotations)
* Merged all JavaDoc headers
* Added `CreationalCommand` interface for `Forward` and `Replace` (old `createStartActivityOptions` and `setupFragmentTransactionAnimation` methods now are deprecated)
* Refactored App and Fragment managers

### CODE REVIEW

**Comment by OsipXD** [comment]
Oh, I found some problems.

**Comment by terrakok** [comment]
This is pure Java library

**Comment by OsipXD** [comment]
Why?
With Kotlin it can be more than Java library. It can become multiplatform library in one click.

**Comment by terrakok** [comment]
This is pure Java library for android applications without dependencies.

**Comment by OsipXD** [comment]
Ok. Got it. Question closed.

But how about `CreationalCommand` interface? 
It can help make code cleaner and restrict types that can be passed to `createStartActivityOptions` and `setupFragmentTransactionAnimation`. What you think about it?

**Pull request closed without merging**
